[project]
name = "amtrak-status"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cairosvg>=2.8.2",
    "httpx>=0.28.1",
    "pillow>=11.0.0",
    "svgwrite>=1.4.3",
]
